name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  doctest:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Test code examples for the pulse paper
      run: |
        python -m pip install --upgrade pip
        pip install qutip-qip[full]==0.1.0 joblib
        pytest *.py --suppress-no-test-exit-code
